# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  Premake_config = debug
  GLFW_config = debug
  glad_config = debug
  Ray_config = debug
  RayUI_config = debug

else ifeq ($(config),release)
  Premake_config = release
  GLFW_config = release
  glad_config = release
  Ray_config = release
  RayUI_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := Premake GLFW glad Ray RayUI

.PHONY: all clean help $(PROJECTS) Dependencies

all: $(PROJECTS)

Dependencies: GLFW Premake glad

Premake:
ifneq (,$(Premake_config))
	@echo "==== Building Premake ($(Premake_config)) ===="
	@${MAKE} --no-print-directory -C vendor/premake -f Makefile config=$(Premake_config)
endif

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C Ray/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

glad:
ifneq (,$(glad_config))
	@echo "==== Building glad ($(glad_config)) ===="
	@${MAKE} --no-print-directory -C Ray/vendor/glad -f Makefile config=$(glad_config)
endif

Ray: GLFW glad
ifneq (,$(Ray_config))
	@echo "==== Building Ray ($(Ray_config)) ===="
	@${MAKE} --no-print-directory -C Ray -f Makefile config=$(Ray_config)
endif

RayUI: Ray GLFW glad
ifneq (,$(RayUI_config))
	@echo "==== Building RayUI ($(RayUI_config)) ===="
	@${MAKE} --no-print-directory -C RayUI -f Makefile config=$(RayUI_config)
endif

clean:
	@${MAKE} --no-print-directory -C vendor/premake -f Makefile clean
	@${MAKE} --no-print-directory -C Ray/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C Ray/vendor/glad -f Makefile clean
	@${MAKE} --no-print-directory -C Ray -f Makefile clean
	@${MAKE} --no-print-directory -C RayUI -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   Premake"
	@echo "   GLFW"
	@echo "   glad"
	@echo "   Ray"
	@echo "   RayUI"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"